language: php
php:
  - 5.4
  - 5.3
  #- hhvm
services:
  - redis-server
before_script:
  - composer install --dev --prefer-source --no-interaction
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage


script:
 - php -v
  #- phpunit --coverage-xml
  #- phpunit  --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage tests

